plugins {
    id 'java'
    id 'com.diffplug.spotless' version '8.10.2' apply false
}

group = 'dev.ss'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

allprojects {
    apply plugin: 'com.diffplug.spotless'

    spotless {
        java {
            googleJavaFormat()
            removeUnusedImports()
            formatAnnotations()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
